# This rule is not used by the project galactic-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to galactic.datumapis.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: galactic-operator
    app.kubernetes.io/managed-by: kustomize
  name: vpc-viewer-role
rules:
- apiGroups:
  - galactic.datumapis.com
  resources:
  - vpcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - galactic.datumapis.com
  resources:
  - vpcs/status
  verbs:
  - get
