# This rule is not used by the project galactic-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the galactic.datumapis.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: galactic-operator
    app.kubernetes.io/managed-by: kustomize
  name: vpcattachment-editor-role
rules:
- apiGroups:
  - galactic.datumapis.com
  resources:
  - vpcattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - galactic.datumapis.com
  resources:
  - vpcattachments/status
  verbs:
  - get
