apiVersion: galactic.datumapis.com/v1alpha
kind: VPC
metadata:
  labels:
    app.kubernetes.io/name: galactic-operator
    app.kubernetes.io/managed-by: kustomize
  name: vpc-sample
spec:
  # TODO(user): Add fields here
